name: flutter_blocs
description: Demo Flutter app on BLoCs.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  meta: ^1.1.7

  equatable: 0.1.6
  bloc: ^0.8.2
  flutter_bloc: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
